### ISSUE TITLE
什么时候支持一下评论功能

### ISSUE THREAD

**Issue by McKinleyLu** [fan-lv/Fan#13]
什么时候支持一下评论功能

**Comment by fan-lv** [comment]
已经集成了Gitment评论功能，但是由于某些不确定因素（网速），会导致登录授权GitHub时间过长，登录失败。

使用方法：

在根目录的 _config.yml 中添加下面代码
```
# 评论
comments:
  gitment:
    enable: true
    owner: '' // github 的 ID 或用户名
    repo: '' // 用于存储评论的 GitHub 仓库名称
    client_id: '' // 注册 gitment 获得的 client_id
    client_secret: '' // 注册 gitment 获得的 client_secret
```
