### ISSUE TITLE
配置了gitment却不显示

### ISSUE THREAD

**Issue by F-Unction** [fan-lv/Fan#24]
`_config.yml`
```yml
comments:
  gitment:
    owner: 'F-Unction'
    repo: 'git@github.com:F-Unction/f-unction.github.io.git'
    client_id: 'bca5d27xxxxxxxxxed82'
    client_secret: '497a7994518727xxxxxxxxxxxxx2b7403294e401'
```
`themes/Fan/_config.yml`
```yml
comments:
    enable: true
```
实际效果 
![深度截图_选择区域_20200501094850](https://user-images.githubusercontent.com/51352133/80774997-02b29c00-8b91-11ea-8ada-259212b1a22c.png)

**Comment by fan-lv** [comment]
```
comments:
  gitment:
    enable: true
    owner: 'F-Unction'
    repo: 'git@github.com:F-Unction/f-unction.github.io.git'
    client_id: 'bca5d27xxxxxxxxxed82'
    client_secret: '497a7994518727xxxxxxxxxxxxx2b7403294e401'
```
需要在这里设置 enable
