### ISSUE TITLE
404页面问题

### ISSUE THREAD

**Issue by Jiaoding** [fan-lv/Fan#26]
hexo new page 404后添加title: Page Not Found，permalink: /404，页面的确转跳404，但是标题是menu.Page Not Found

![如图](https://jiao-ding-com.oss-cn-hangzhou.aliyuncs.com/1.png)

**Comment by Jiaoding** [comment]
有解决办法吗？

**Comment by Jiaoding** [comment]
@fan-lv

**Comment by fan-lv** [comment]
404的md文件中有写上title吗
```
---
title: 分类
type: "categories"
---
```

**Comment by Jiaoding** [comment]
title为Page Not Found，显示的是menu.Page Not Found
没有title时，显示的是menu.

**Comment by fan-lv** [comment]
![image](https://user-images.githubusercontent.com/24888867/91786649-ad6bc180-ec3a-11ea-8a86-fe07358d81bb.png)
需要在语言的文件下面配置
![image](https://user-images.githubusercontent.com/24888867/91786687-c1172800-ec3a-11ea-8b98-2088a090d9de.png)

**Comment by Jiaoding** [comment]
404目录在主目录下面的source目录下，404目录下的index.md填写的是：
```
---
title: 页面无法显示
type: "commonweal"
permalink: /404
---
```
zh-Hans.yml填的是：
```
menu:
  home: 首页
  archives: 归档
  categories: 分类
  tags: 标签
  about: 关于
  search: 搜索
  schedule: 日程表
  sitemap: 站点地图
  commonweal: 页面无法显示
  friendlink: 友链

```
页面结果是：
如同我提问附上的图片一样，menu.页面无法显示
@fan-lv

**Comment by fan-lv** [comment]
按照你说的如果在404页面title写成：
```
---
title: 页面无法显示
type: "commonweal"
permalink: /404
---
```
则需要在zh-Hans.yml填写：
```
menu:
  home: 首页
  archives: 归档
  categories: 分类
  tags: 标签
  about: 关于
  search: 搜索
  schedule: 日程表
  sitemap: 站点地图
  commonweal: 页面无法显示
  friendlink: 友链
  页面无法显示:页面无法显示
```

---

同理，可以把404页面的title写成：
```
---
title: 404
type: "commonweal"
permalink: /404
---
```
在zh-Hans.yml填写：
```
menu:
  home: 首页
  archives: 归档
  categories: 分类
  tags: 标签
  about: 关于
  search: 搜索
  schedule: 日程表
  sitemap: 站点地图
  commonweal: 页面无法显示
  friendlink: 友链
  404:页面无法显示
```
